
services:
  nanosaur-perception:
    image: nanosaur/perception:latest
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    command: >
      ros2 launch nanosaur_perception perception.launch.py ${COMMANDS}
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /run/jtop.sock:/run/jtop.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/admin/.Xauthority:rw
