name: Dependabot Workflow
on:
  pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:

  dependabot:
    name: "Build Docker image develop"
    runs-on: self-hosted
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: |
        if ${{ startsWith(github.ref, 'refs/tags/') }} ; then
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
        else
          echo ::set-output name=tag::${GITHUB_REF/refs\/heads\//}
        fi
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Docker info
      shell: bash
      run: docker info
    - name: Build Docker
      shell: bash
      id: docker_build
      run: |
        BRANCH_NAME=${{ steps.extract_tag.outputs.tag }}
        TERM=xterm bash nanosaur_perception/scripts/docker_builder.sh -ci --branch $BRANCH_NAME
    - name: Login to DockerHub
      uses: docker/login-action@v1.12.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker
      shell: bash
      id: docker_push
      run: |
        BRANCH_NAME=${{ steps.extract_tag.outputs.tag }}
        TERM=xterm bash nanosaur_perception/scripts/docker_builder.sh --push --branch $BRANCH_NAME
    - name: Enable auto-merge for Dependabot PRs
      if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}