name: Docker Builder CI

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://jasonet.co/posts/scheduled-actions/
on: [push, workflow_dispatch]

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  docker:
    name: "Build Docker image develop"
    runs-on: self-hosted
    steps:
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: |
        if ${{ startsWith(github.ref, 'refs/tags/') }} ; then
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
        else
          echo ::set-output name=tag::${GITHUB_REF/refs\/heads\//}
        fi
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Docker info
      shell: bash
      run: docker info
    - name: Build Docker
      shell: bash
      id: docker_build
      run: |
        BRANCH_NAME=${{ steps.extract_tag.outputs.tag }}
        TERM=xterm bash nanosaur_perception/scripts/docker_builder.sh -ci --branch $BRANCH_NAME
    - name: Login to DockerHub
      uses: docker/login-action@v1.13.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker
      shell: bash
      id: docker_push
      run: |
        BRANCH_NAME=${{ steps.extract_tag.outputs.tag }}
        TERM=xterm bash nanosaur_perception/scripts/docker_builder.sh --push --branch $BRANCH_NAME
    - name: Push Latest Docker
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        BRANCH_NAME=${{ steps.extract_tag.outputs.tag }}
        TERM=xterm bash nanosaur_perception/scripts/docker_builder.sh --push --branch $BRANCH_NAME --latest

  make_release:
    name: Upload release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Release # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.extract_tag.outputs.tag }}
        generate_release_notes: true
        draft: false
        prerelease: false

  # https://github.com/peter-evans/dockerhub-description
  update_docker_description:
    name: Update docker description
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: nanosaur/perception
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md

  notify:
    name: "Notify socials"
    if: startsWith(github.ref, 'refs/tags/')
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      # https://github.community/t/how-to-get-just-the-tag-name/16241/11
    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project **{{ EVENT_PAYLOAD.repository.full_name }}** has been deployed v${{ steps.extract_tag.outputs.tag }}.'